// <auto-generated />
using System;
using SIPS.PostgreSQL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SIPS.PostgreSQL.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20250123125850_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("FromBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frombic");

                    b.Property<byte[]>("Message")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("message");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messagetype");

                    b.Property<byte[]>("Response")
                        .HasColumnType("bytea")
                        .HasColumnName("response");

                    b.Property<string>("ToBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tobic");

                    b.HasKey("Id")
                        .HasName("pk_isomessages");

                    b.ToTable("isomessages", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CategoryPurpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categorypurpose");

                    b.Property<string>("CreditorAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoraccount");

                    b.Property<string>("CreditorAccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoraccounttype");

                    b.Property<string>("CreditorAgentBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoragentbic");

                    b.Property<string>("CreditorIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditorissuer");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditorname");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("DebtorAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoraccount");

                    b.Property<string>("DebtorAccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoraccounttype");

                    b.Property<string>("DebtorAgentBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoragentbic");

                    b.Property<string>("DebtorIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtorissuer");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtorname");

                    b.Property<string>("EndToEndId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endtoendid");

                    b.Property<string>("FromBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frombic");

                    b.Property<int>("ISOMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("isomessageid");

                    b.Property<string>("LocalInstrument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("localinstrument");

                    b.Property<string>("RemittanceInformation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remittanceinformation");

                    b.Property<string>("TxId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("txid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("ISOMessageId")
                        .HasDatabaseName("ix_transactions_isomessageid");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.Transaction", b =>
                {
                    b.HasOne("SIPS.PostgreSQL.Models.ISOMessage", "ISOMessage")
                        .WithMany("Transactions")
                        .HasForeignKey("ISOMessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_isomessages_isomessageid");

                    b.Navigation("ISOMessage");
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessage", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
