// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIPS.PostgreSQL.Persistence;

#nullable disable

namespace SIPS.PostgreSQL.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20260208144238_AddStatusDeDupColumns")]
    partial class AddStatusDeDupColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additionalinfo");

                    b.Property<string>("BizMsgIdr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bizmsgidr");

                    b.Property<string>("CoreBankResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("corebankresponse");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("EndToEndId")
                        .HasColumnType("text")
                        .HasColumnName("endtoendid");

                    b.Property<string>("FromBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frombic");

                    b.Property<byte[]>("Message")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("message");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messagetype");

                    b.Property<string>("MsgDefIdr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("msgdefidr");

                    b.Property<string>("MsgId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("msgid");

                    b.Property<string>("Pacs002Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pacs002role");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<byte[]>("Response")
                        .HasColumnType("bytea")
                        .HasColumnName("response");

                    b.Property<string>("ReturnDedupKey")
                        .HasColumnType("text")
                        .HasColumnName("returndedupkey");

                    b.Property<string>("ReturnId")
                        .HasColumnType("text")
                        .HasColumnName("returnid");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tobic");

                    b.Property<string>("TxId")
                        .HasColumnType("text")
                        .HasColumnName("txid");

                    b.Property<string>("UETR")
                        .HasColumnType("text")
                        .HasColumnName("uetr");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_isomessages");

                    b.HasIndex("TxId")
                        .HasDatabaseName("ix_iso_msg_txid_anchor");

                    b.HasIndex("UETR")
                        .HasDatabaseName("ix_iso_msg_uetr");

                    b.HasIndex("MessageType", "MsgId")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_msg_type_msgid")
                        .HasFilter("\"msgid\" IS NOT NULL AND \"msgid\" <> ''");

                    b.HasIndex("MessageType", "ReturnDedupKey")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_msg_type_rtr_dedup")
                        .HasFilter("\"returndedupkey\" IS NOT NULL AND \"returndedupkey\" <> ''");

                    b.HasIndex("MessageType", "ReturnId")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_msg_type_rtrid")
                        .HasFilter("\"returnid\" IS NOT NULL AND \"returnid\" <> ''");

                    b.HasIndex("MessageType", "TxId")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_msg_type_txid")
                        .HasFilter("\"txid\" IS NOT NULL AND \"txid\" <> ''");

                    b.ToTable("isomessages", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessageStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additionalinfo");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("ISOMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("isomessageid");

                    b.Property<byte[]>("Message")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("message");

                    b.Property<string>("MessageRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messagerole");

                    b.Property<string>("MsgId")
                        .HasColumnType("text")
                        .HasColumnName("msgid");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<byte[]>("Response")
                        .HasColumnType("bytea")
                        .HasColumnName("response");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_isomessagestatuses");

                    b.HasIndex("ISOMessageId", "MessageRole", "Status", "MsgId")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_status_dedup");

                    b.ToTable("isomessagestatuses", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CategoryPurpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categorypurpose");

                    b.Property<string>("CreditorAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoraccount");

                    b.Property<string>("CreditorAccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoraccounttype");

                    b.Property<string>("CreditorAgentBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoragentbic");

                    b.Property<string>("CreditorIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditorissuer");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditorname");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("DebtorAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoraccount");

                    b.Property<string>("DebtorAccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoraccounttype");

                    b.Property<string>("DebtorAgentBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoragentbic");

                    b.Property<string>("DebtorIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtorissuer");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtorname");

                    b.Property<string>("EndToEndId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endtoendid");

                    b.Property<string>("FromBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frombic");

                    b.Property<int>("ISOMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("isomessageid");

                    b.Property<string>("LocalInstrument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("localinstrument");

                    b.Property<string>("RemittanceInformation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remittanceinformation");

                    b.Property<string>("TxId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("txid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("EndToEndId")
                        .HasDatabaseName("ix_transactions_endtoendid");

                    b.HasIndex("ISOMessageId")
                        .HasDatabaseName("ix_transactions_isomessageid");

                    b.HasIndex("TxId")
                        .HasDatabaseName("ix_transactions_txid");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessageStatus", b =>
                {
                    b.HasOne("SIPS.PostgreSQL.Models.ISOMessage", "ISOMessage")
                        .WithMany("Statuses")
                        .HasForeignKey("ISOMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_isomessagestatuses_isomessages_isomessageid");

                    b.Navigation("ISOMessage");
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.Transaction", b =>
                {
                    b.HasOne("SIPS.PostgreSQL.Models.ISOMessage", "ISOMessage")
                        .WithMany("Transactions")
                        .HasForeignKey("ISOMessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_isomessages_isomessageid");

                    b.Navigation("ISOMessage");
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessage", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
