// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIPS.PostgreSQL.Persistence;

#nullable disable

namespace SIPS.PostgreSQL.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20260925120000_AddPapssEventProvenance")]
    partial class AddPapssEventProvenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additionalinfo");

                    b.Property<string>("BizMsgIdr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bizmsgidr");

                    b.Property<string>("BusinessService")
                        .HasColumnType("text")
                        .HasColumnName("businessservice");

                    b.Property<string>("CoreBankResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("corebankresponse");

                    b.Property<int>("CoreBankRetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("corebankretrycount");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("EndToEndId")
                        .HasColumnType("text")
                        .HasColumnName("endtoendid");

                    b.Property<string>("FromBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frombic");

                    b.Property<byte[]>("Message")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("message");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messagetype");

                    b.Property<string>("MsgDefIdr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("msgdefidr");

                    b.Property<string>("MsgId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("msgid");

                    b.Property<string>("Pacs002Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pacs002role");

                    b.Property<byte[]>("PapssDecision")
                        .HasColumnType("bytea")
                        .HasColumnName("papssdecision");

                    b.Property<string>("PapssDecisionAdmissionCode")
                        .HasColumnType("text")
                        .HasColumnName("papssdecisionadmissioncode");

                    b.Property<DateTimeOffset?>("PapssDecisionFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("papssdecisionfailedat");

                    b.Property<string>("PapssDecisionFailureCode")
                        .HasColumnType("text")
                        .HasColumnName("papssdecisionfailurecode");

                    b.Property<DateTimeOffset?>("PapssDecisionPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("papssdecisionpublishedat");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<byte[]>("Response")
                        .HasColumnType("bytea")
                        .HasColumnName("response");

                    b.Property<string>("ReturnDedupKey")
                        .HasColumnType("text")
                        .HasColumnName("returndedupkey");

                    b.Property<string>("ReturnId")
                        .HasColumnType("text")
                        .HasColumnName("returnid");

                    b.Property<int>("Round")
                        .HasColumnType("integer")
                        .HasColumnName("round");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tobic");

                    b.Property<string>("TxId")
                        .HasColumnType("text")
                        .HasColumnName("txid");

                    b.Property<string>("UETR")
                        .HasColumnType("text")
                        .HasColumnName("uetr");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_isomessages");

                    b.HasIndex("TxId")
                        .HasDatabaseName("ix_iso_msg_txid_anchor");

                    b.HasIndex("UETR")
                        .HasDatabaseName("ix_iso_msg_uetr");

                    b.HasIndex("MessageType", "MsgId")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_msg_type_msgid")
                        .HasFilter("\"msgid\" IS NOT NULL AND \"msgid\" <> ''");

                    b.HasIndex("MessageType", "ReturnDedupKey")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_msg_type_rtr_dedup")
                        .HasFilter("\"returndedupkey\" IS NOT NULL AND \"returndedupkey\" <> ''");

                    b.HasIndex("MessageType", "ReturnId")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_msg_type_rtrid")
                        .HasFilter("\"returnid\" IS NOT NULL AND \"returnid\" <> ''");

                    b.HasIndex("MessageType", "TxId")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_msg_type_txid")
                        .HasFilter("\"txid\" IS NOT NULL AND \"txid\" <> ''");

                    b.HasIndex("TxId", "MessageType")
                        .HasDatabaseName("ix_iso_msg_txid_msgtype");

                    b.HasIndex("BusinessService", "PapssDecisionPublishedAt", "PapssDecisionFailedAt", "Id")
                        .HasDatabaseName("ix_iso_msg_papss_decision_pending");

                    b.ToTable("isomessages", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessageStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additionalinfo");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("ISOMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("isomessageid");

                    b.Property<byte[]>("Message")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("message");

                    b.Property<string>("MessageRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messagerole");

                    b.Property<string>("MsgId")
                        .HasColumnType("text")
                        .HasColumnName("msgid");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<byte[]>("Response")
                        .HasColumnType("bytea")
                        .HasColumnName("response");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_isomessagestatuses");

                    b.HasIndex("ISOMessageId", "MessageRole", "Status", "MsgId")
                        .IsUnique()
                        .HasDatabaseName("ux_iso_status_dedup");

                    b.ToTable("isomessagestatuses", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.PapssOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .HasColumnType("text")
                        .HasColumnName("accountid");

                    b.Property<string>("AccountName")
                        .HasColumnType("text")
                        .HasColumnName("accountname");

                    b.Property<string>("AccountType")
                        .HasColumnType("text")
                        .HasColumnName("accounttype");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additionalinfo");

                    b.Property<string>("AdmissionCode")
                        .HasColumnType("text")
                        .HasColumnName("admissioncode");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,5)")
                        .HasColumnName("amount");

                    b.Property<string>("BankDeliveryState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("bankdeliverystate");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completedat");

                    b.Property<string>("CounterpartyBic")
                        .HasColumnType("text")
                        .HasColumnName("counterpartybic");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadlineat");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<string>("EndToEndId")
                        .HasColumnType("text")
                        .HasColumnName("endtoendid");

                    b.Property<string>("GatewayState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gatewaystate");

                    b.Property<int?>("IsoMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("isomessageid");

                    b.Property<string>("LocalInstrument")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("localinstrument");

                    b.Property<string>("MsgId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("msgid");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation");

                    b.Property<string>("OriginalEndToEndId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("originalendtoendid");

                    b.Property<Guid?>("OriginalOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("originaloperationid");

                    b.Property<string>("OriginalTxId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("originaltxid");

                    b.Property<string>("PapssOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("papssoutcome");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("paymentstatus");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reasoncode");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receivedat");

                    b.Property<string>("RequestFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("requestfingerprint");

                    b.Property<string>("RequestMessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("requestmessageid");

                    b.Property<string>("ReturnId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("returnid");

                    b.Property<byte[]>("SignedRequest")
                        .HasColumnType("bytea")
                        .HasColumnName("signedrequest");

                    b.Property<byte[]>("SignedResponse")
                        .HasColumnType("bytea")
                        .HasColumnName("signedresponse");

                    b.Property<DateTimeOffset?>("SourceCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sourcecreatedat");

                    b.Property<DateTimeOffset?>("StatusAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("statusat");

                    b.Property<bool>("StatusConflict")
                        .HasColumnType("boolean")
                        .HasColumnName("statusconflict");

                    b.Property<string>("StatusReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("statusreasoncode");

                    b.Property<string>("TxId")
                        .HasColumnType("text")
                        .HasColumnName("txid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("VerificationId")
                        .HasColumnType("text")
                        .HasColumnName("verificationid");

                    b.Property<bool?>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_papss_operations");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_papss_op_completed_at");

                    b.HasIndex("EndToEndId")
                        .HasDatabaseName("ix_papss_op_end_to_end_id");

                    b.HasIndex("IsoMessageId")
                        .HasDatabaseName("ix_papss_op_iso_message");

                    b.HasIndex("MsgId")
                        .HasDatabaseName("ix_papss_op_msg_id");

                    b.HasIndex("OriginalOperationId")
                        .HasDatabaseName("ix_papss_op_original");

                    b.HasIndex("TxId")
                        .HasDatabaseName("ix_papss_op_tx_id");

                    b.HasIndex("VerificationId")
                        .HasDatabaseName("ix_papss_op_verification_id");

                    b.HasIndex("Direction", "RequestMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_papss_op_direction_request_msg");

                    b.HasIndex("Direction", "ReturnId")
                        .IsUnique()
                        .HasDatabaseName("ux_papss_op_return_id")
                        .HasFilter("operation = 'RETURN' AND returnid IS NOT NULL");

                    b.HasIndex("Direction", "Operation", "TxId")
                        .IsUnique()
                        .HasDatabaseName("ux_papss_op_payment_txid")
                        .HasFilter("operation = 'PAYMENT' AND txid IS NOT NULL");

                    b.ToTable("papss_operations", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.PapssOperationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,5)")
                        .HasColumnName("amount");

                    b.Property<string>("AmountSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("amountsource");

                    b.Property<string>("CategoryPurposeSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("categorypurposesource");

                    b.Property<string>("Correlation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("correlation");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Disposition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("disposition");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("eventtype");

                    b.Property<string>("FieldProvenance")
                        .HasColumnType("text")
                        .HasColumnName("fieldprovenance");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("messagetype");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("note");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operationid");

                    b.Property<string>("OriginalEndToEndId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("originalendtoendid");

                    b.Property<string>("OriginalMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("originalmessageid");

                    b.Property<string>("OriginalMessageType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("originalmessagetype");

                    b.Property<string>("OriginalTxId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("originaltxid");

                    b.Property<int>("PushAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("pushattempts");

                    b.Property<DateTimeOffset?>("PushDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pushdeliveredat");

                    b.Property<string>("PushLastError")
                        .HasColumnType("text")
                        .HasColumnName("pushlasterror");

                    b.Property<DateTimeOffset?>("PushNextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pushnextattemptat");

                    b.Property<string>("PushState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pushstate");

                    b.Property<string>("RawEvidenceReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rawevidencereference");

                    b.Property<byte[]>("RawXml")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("rawxml");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reasoncode");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receivedat");

                    b.Property<string>("SourceMessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sourcemessageid");

                    b.Property<string>("Status")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_papss_operation_events");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("ix_papss_event_operation");

                    b.HasIndex("EventType", "Disposition")
                        .HasDatabaseName("ix_papss_event_type_disposition");

                    b.HasIndex("EventType", "SourceMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_papss_event_type_source_msg");

                    b.HasIndex("PushState", "PushNextAttemptAt")
                        .HasDatabaseName("ix_papss_event_push_due");

                    b.ToTable("papss_operation_events", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.PapssOutboundResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdmissionCode")
                        .HasColumnType("text")
                        .HasColumnName("admissioncode");

                    b.Property<DateTimeOffset?>("AdmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admittedat");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("BizMsgIdr")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bizmsgidr");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("lasterror");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("messagetype");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nextattemptat");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operationid");

                    b.Property<byte[]>("SignedXml")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("signedxml");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submittedat");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_papss_outbound_responses");

                    b.HasIndex("BizMsgIdr")
                        .IsUnique()
                        .HasDatabaseName("ux_papss_response_biz_msg_idr");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_papss_response_operation");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("ix_papss_response_due");

                    b.ToTable("papss_outbound_responses", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CategoryPurpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categorypurpose");

                    b.Property<string>("CreditorAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoraccount");

                    b.Property<string>("CreditorAccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoraccounttype");

                    b.Property<string>("CreditorAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoraddress");

                    b.Property<string>("CreditorAgentBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditoragentbic");

                    b.Property<string>("CreditorIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditorissuer");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditorname");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("DebtorAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoraccount");

                    b.Property<string>("DebtorAccountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoraccounttype");

                    b.Property<string>("DebtorAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoraddress");

                    b.Property<string>("DebtorAgentBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtoragentbic");

                    b.Property<string>("DebtorIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtorissuer");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtorname");

                    b.Property<string>("EndToEndId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endtoendid");

                    b.Property<string>("FromBIC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frombic");

                    b.Property<int>("ISOMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("isomessageid");

                    b.Property<string>("LocalInstrument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("localinstrument");

                    b.Property<string>("RemittanceInformation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remittanceinformation");

                    b.Property<string>("TxId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("txid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("EndToEndId")
                        .HasDatabaseName("ix_transactions_endtoendid");

                    b.HasIndex("ISOMessageId")
                        .HasDatabaseName("ix_transactions_isomessageid");

                    b.HasIndex("TxId")
                        .HasDatabaseName("ix_transactions_txid");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessageStatus", b =>
                {
                    b.HasOne("SIPS.PostgreSQL.Models.ISOMessage", "ISOMessage")
                        .WithMany("Statuses")
                        .HasForeignKey("ISOMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_isomessagestatuses_isomessages_isomessageid");

                    b.Navigation("ISOMessage");
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.PapssOperation", b =>
                {
                    b.HasOne("SIPS.PostgreSQL.Models.PapssOperation", "OriginalOperation")
                        .WithMany()
                        .HasForeignKey("OriginalOperationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_papss_operations_papss_operations_originaloperationid");

                    b.Navigation("OriginalOperation");
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.PapssOperationEvent", b =>
                {
                    b.HasOne("SIPS.PostgreSQL.Models.PapssOperation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_papss_operation_events_papss_operations_operationid");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.PapssOutboundResponse", b =>
                {
                    b.HasOne("SIPS.PostgreSQL.Models.PapssOperation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_papss_outbound_responses_papss_operations_operationid");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.Transaction", b =>
                {
                    b.HasOne("SIPS.PostgreSQL.Models.ISOMessage", "ISOMessage")
                        .WithMany("Transactions")
                        .HasForeignKey("ISOMessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_isomessages_isomessageid");

                    b.Navigation("ISOMessage");
                });

            modelBuilder.Entity("SIPS.PostgreSQL.Models.ISOMessage", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
