using System.Text.Json;
using System.Text.Json.Serialization;
using SIPS.Adapter;
using SIPS.ISO20022.Helpers;
using SIPS.ISO20022.Interfaces;
using SIPS.ISO20022.Options;
using SIPS.PostgreSQL.Interfaces;
using SIPS.XMLDsig.Xades.Interfaces;
using SIPS.XMLDsig.Xades.Services;
using Microsoft.Extensions.Logging;
using SIPS.Core.Services.Verification;
using SIPS.Core.Services.ISOParsers;
using SIPS.Core.Services.Callback;
using SIPS.Core.Services.Responses;
using SIPS.Core.Services.Persistence;
using SIPS.Core.Services.Correlation;
using SIPS.Core.Services.Abstractions;
using SIPS.Core.Services.Implementations;
using SIPS.Core.Services.Metrics;
using SIPS.PostgreSQL.Enums;
using System.Text.Json.Nodes;
using SIPS.ISO20022.Models.DTOs;
using SIPS.ISO20022.Models.DTOs.CB;
using SIPS.ISO20022.Enums;
using Microsoft.Extensions.Options;
using SIPS.Core.Options;
using static SIPS.Core.Constants;
namespace SIPS.Core.Services;

/// <summary>
/// Handles incoming pacs.008 payment requests from SmartVista IPS.
/// 
/// IMPORTANT: SmartVista IPS Switch Behavior
/// ==========================================
/// When we receive a pacs.008, it has been REGENERATED by the SmartVista switch:
/// 
/// 1. Original Bank → Switch:
///    - Sending bank creates pacs.008 with their BizMsgIdr, CreDt, signature
///    
/// 2. Switch → Us (this handler):
///    - Switch REGENERATES AppHdr with NEW BizMsgIdr and CreDt
///    - Switch PRESERVES the original bank's signature (document:Sgntr)
///    - Switch PRESERVES the entire document payload (FIToFICstmrCdtTrf)
///    - The AppHdr.Fr will be the switch ID (e.g., "FP"), not the original bank
///    
/// 3. Our Response (pacs.002):
///    - We respond with pacs.002 immediately (ACSC status)
///    - Rltd block references the SWITCH-GENERATED message we received
///    - NOT the original bank's message (which we never saw)
///    - Transaction remains Pending until we receive completion notification
///    
/// 4. Completion Flow:
///    - Switch forwards our pacs.002 to the original bank
///    - Switch sends us a completion notification (pacs.002) after settlement
///    - We respond to the completion notification
///    - Only then do we call CoreBank to credit the account
///    
/// CORRELATION:
/// ===========
/// - We use TxId for correlation (constant throughout the flow)
/// - BizMsgIdr changes at every hop and cannot be used for correlation
/// - The signature verification proves the original bank's authenticity
/// </summary>
public sealed class IncomingTransactionHandler(
    ISO20022Options options,
    ILogger<IncomingTransactionHandler> logger,
    INativeSigner signer,
    IJsonAdapter jsonAdapter,
    IPaymentRequestParser parser,
    ICallbackClient callback,
    IResponseFactory responseFactory,
    ICorrelationService correlation,
    IInboundMessageService inbound,
    ICallbackOrchestrator callbacks,
    IISOMessageService isoService,
    IOptions<CoreOptions> coreOptions
    ) : IIncomingTransactionHandler
{
    private readonly ISO20022Options _callbackLinks = options;
    private readonly ILogger<IncomingTransactionHandler> _logger = logger;
    private readonly INativeSigner _signer = signer;
    private readonly IJsonAdapter _jsonAdapter = jsonAdapter;
    private readonly IPaymentRequestParser _parser = parser;
    private readonly ICallbackClient _callback = callback;
    private readonly IResponseFactory _responses = responseFactory;
    private readonly ICorrelationService _correlation = correlation;
    private readonly IInboundMessageService _inbound = inbound;
    private readonly ICallbackOrchestrator _callbacks = callbacks;
    private readonly IISOMessageService _isoService = isoService;
    private readonly CoreOptions _core = coreOptions.Value;
    private readonly JsonSerializerOptions _jsonSerializerOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) }
    };

    // Compatibility constructor for tests and existing code paths (14 args)
    public IncomingTransactionHandler(
        ISO20022Options options,
        ILogger<IncomingTransactionHandler> logger,
        IInterfaceHttpClient httpClient,
        INativeSigner signer,
        INativeVerifier verifier,
        IJsonAdapter jsonAdapter,
        IIncomingRecorder record,
        ISignatureService signature,
        IPaymentRequestParser parser,
        ICallbackClient callback,
        IResponseFactory responseFactory,
        IPersistenceGateway persistence,
        ICorrelationService correlation,
        IOptions<CoreOptions> coreOptions)
        : this(options, logger, signer, jsonAdapter, parser, callback, responseFactory, correlation,
              new InboundMessageService(signature),
              new CallbackOrchestrator(),
              new ISOMessageService(persistence),
              coreOptions)
    {
    }

    // Legacy Primary Constructor (17 args) - Restored for test compatibility
    public IncomingTransactionHandler(
        ISO20022Options options,
        ILogger<IncomingTransactionHandler> logger,
        IInterfaceHttpClient httpClient,
        INativeSigner signer,
        INativeVerifier verifier,
        IJsonAdapter jsonAdapter,
        IIncomingRecorder record,
        ISignatureService signature,
        IPaymentRequestParser parser,
        ICallbackClient callback,
        IResponseFactory responseFactory,
        IPersistenceGateway persistence,
        ICorrelationService correlation,
        IInboundMessageService inbound,
        ICallbackOrchestrator callbacks,
        IISOMessageService isoService,
        IOptions<CoreOptions> coreOptions)
        : this(options, logger, signer, jsonAdapter, parser, callback, responseFactory, correlation, inbound, callbacks, isoService, coreOptions)
    {
    }
    public async Task<string> HandleAsync(string message, CancellationToken ct)
    {
        using var _totalTrack = SipsMetrics.TrackStep("Incoming", "Transaction", "Total");
        var sw = System.Diagnostics.Stopwatch.StartNew();
        string path = "Normal";
        string cid = _correlation.Create();

        // [CHANGE GUARD]: Internal watchdog budget ensures contractual Compliance with BPC 10s SLA.
        using var globalCts = CancellationTokenSource.CreateLinkedTokenSource(ct);
        globalCts.CancelAfter(TimeSpan.FromSeconds(_core.CallbackInternalBudgetSeconds > 0 ? _core.CallbackInternalBudgetSeconds : 9));
        var gct = globalCts.Token;

        PaymentRequestBuilder.Request? request = null;
        SIPS.PostgreSQL.Models.ISOMessage? record = null;
        try
        {
            // Step 1: Verify signature and parse message via helper
            bool isValid = false;
            using (SipsMetrics.TrackStep("Incoming", "Transaction", "ParsingAndSignature"))
            {
                var (valid, parsedRequest) = await _inbound.VerifyAndParseAsync(
                    message,
                    (xml) =>
                    {
                        if (!_parser.TryParse(xml, out var req)) return (false, (PaymentRequestBuilder.Request?)null);
                        return (true, req);
                    },
                    gct,
                    cid);
                isValid = valid;
                request = parsedRequest;
            }
            if (!isValid || request == null)
            {
                path = "ParseFail";
                // [PROTOCOL]: admi.002 for technical/protocol errors (SmartVista spec)
                var err = SipsReject.Create(message, AdminRejectReasonCodes.InvalidXml, "Failed to verify signature or parse ISO20022 message.");
                return FinalizeResponse(err, cid, sw, path);
            }

            // [INVARIANT A]: Hard-reject missing TxId (required for de-duplication)
            if (string.IsNullOrWhiteSpace(request.TxId))
            {
                path = "MissingTxId";
                _logger.LogWarning("[{CorrelationId}] [METRIC:ISO_PATH=MissingTxId] Rejecting message with missing TxId. MsgId={MsgId}", cid, request.MsgId);
                // [PROTOCOL]: admi.002 for mandatory element missing (SmartVista spec)
                var err = SipsReject.Create(message, AdminRejectReasonCodes.MandatoryElementMissing, "Transaction ID (TxId) is mandatory for de-duplication.");
                return FinalizeResponse(err, cid, sw, path);
            }

            // Step 2: [GOLD PATTERN] INSERT-First De-duplication
            bool isNew = false;
            using (SipsMetrics.TrackStep("Incoming", "Transaction", "DbSave"))
            {
                var tryRecordResult = await _isoService.TryRecordIncomingTransactionAsync(request, message, gct);
                record = tryRecordResult.Message;
                isNew = tryRecordResult.IsNew;
            }

            if (record == null)
            {
                path = "DbInsertFailed";
                _logger.LogError("[{CorrelationId}] Failed to insert or retrieve ISOMessage for TxId {TxId}. Rejecting for safety.", cid, request.TxId);
                // [PROTOCOL]: admi.002 for infrastructure/persistence failure (SmartVista spec)
                var err = SipsReject.Create(message, AdminRejectReasonCodes.TechnicalError, "Infrastructure failure: unable to record transaction.");
                return FinalizeResponse(err, cid, sw, path);
            }

            // [FOLLOWER LOGIC]: Check if this is a duplicate (existing record from concurrent/retry request)
            if (!isNew)
            {
                if (record.Response != null && record.Response.Length > 0)
                {
                    path = "ReplayStored";
                    _logger.LogInformation("[{CorrelationId}] [METRIC:ISO_PATH=ReplayStored] Structural de-duplication: Replaying stored response for TxId {TxId}. Status={Status}", cid, request.TxId, record.Status);
                    var storedResponse = System.Text.Encoding.UTF8.GetString(record.Response);
                    if (StoredResponseMatchesRequest(storedResponse, request))
                        return FinalizeResponse(storedResponse, cid, sw, path);

                    path = "InvalidStoredResponse";
                    _logger.LogError("[{CorrelationId}] Refusing to replay a stored response whose correlation fields do not match TxId {TxId}.", cid, request.TxId);
                    var invalidStoredResponse = SipsReject.Create(message, AdminRejectReasonCodes.TechnicalError, "Stored response failed correlation validation.");
                    return FinalizeResponse(invalidStoredResponse, cid, sw, path);
                }

                // [FOLLOWER WAIT LOGIC]: If Pending or CheckStatus, wait briefly then re-check
                if (record.Status == TransactionStatus.Pending || record.Status == TransactionStatus.CheckStatus)
                {
                    path = "ConcurrentPending";
                    _logger.LogInformation("[{CorrelationId}] [METRIC:ISO_PATH=ConcurrentPending] Duplicate arrived while Status={Status}. Waiting 500ms for owner to complete...", cid, record.Status);
                    
                    await Task.Delay(500, gct);
                    
                    // Re-fetch to see if owner completed
                    var refreshed = await _isoService.GetInboundMessageByTxIdAsync(request.TxId, gct);
                    if (refreshed?.Response != null && refreshed.Response.Length > 0)
                    {
                        path = "ReplayAfterWait";
                        _logger.LogInformation("[{CorrelationId}] [METRIC:ISO_PATH=ReplayAfterWait] Owner completed. Replaying stored response for TxId {TxId}.", cid, request.TxId);
                        var storedResponse = System.Text.Encoding.UTF8.GetString(refreshed.Response);
                        if (StoredResponseMatchesRequest(storedResponse, request))
                            return FinalizeResponse(storedResponse, cid, sw, path);

                        path = "InvalidStoredResponse";
                        _logger.LogError("[{CorrelationId}] Refusing to replay a newly stored response whose correlation fields do not match TxId {TxId}.", cid, request.TxId);
                        var invalidStoredResponse = SipsReject.Create(message, AdminRejectReasonCodes.TechnicalError, "Stored response failed correlation validation.");
                        return FinalizeResponse(invalidStoredResponse, cid, sw, path);
                    }
                    
                    // Still pending after wait → return admi.002 (duplicate in-process)
                    path = "DuplicatePending";
                    _logger.LogWarning("[{CorrelationId}] [METRIC:ISO_PATH=DuplicatePending] Owner still processing after 500ms. Returning admi.002(DuplicateInProcess) for TxId {TxId}.", cid, request.TxId);
                    
                    var ev = new
                    {
                        schemaVersion = 1,
                        eventId = Guid.NewGuid(),
                        actor = "System",
                        @event = "DuplicateReceivedWhilePending",
                        timestampUtc = DateTimeOffset.UtcNow,
                        correlation = new { transactionId = request.TxId, msgId = request.MsgId, uetr = request.UETR, endToEndId = request.EndToEndId },
                        duplicateBy = "TxId"  // Track which constraint would have fired
                    };
                    await _isoService.AppendAuditLedgerEventAsync(record.Id, ev, gct);
                    
                    // [PROTOCOL]: admi.002 for duplicate message in-process (SmartVista spec)
                    var err = SipsReject.Create(message, AdminRejectReasonCodes.DuplicateMessageInProcess, "Duplicate transaction is being processed by another request.");
                    return FinalizeResponse(err, cid, sw, path);
                }
            }

            // [OWNER LOGIC]: We successfully inserted the record. We are the owner and must call CoreBank.

            // Step 3: Prepare response object
            var response = _responses.BuildPaymentInitial(request);

            try
            {
                // CoreBank Integration (Optional)
                if (_core.IncludeCoreBankOnListing)
                {
                    try
                    {
                        var headers = new Dictionary<string, string>() {
                            { API_Key, _callbackLinks.Key! },
                            { API_Secret, _callbackLinks.Secret! }
                        };
                        // Idempotency key
                        if (!string.IsNullOrWhiteSpace(request.TxId))
                            headers["X-Idempotency-Key"] = request.TxId;
                        if (!string.IsNullOrWhiteSpace(request.TxId))
                            headers["X-Transaction-Id"] = request.TxId;

                        var dto = new CBPaymentRequestDto
                        {
                            FromBIC = request.From ?? string.Empty,
                            LocalInstrument = request.LocalInstrument ?? string.Empty,
                            CategoryPurpose = request.CategoryPurpose ?? string.Empty,
                            EndToEndId = request.EndToEndId ?? string.Empty,
                            TxId = request.TxId ?? string.Empty,
                            Amount = request.Amount,
                            Currency = request.Currency ?? string.Empty,
                            DebtorName = request.Debtor?.Name ?? string.Empty,
                            DebtorAddress = request.Debtor?.Address ?? string.Empty,
                            DebtorAccount = request.Debtor?.Account ?? string.Empty,
                            DebtorAccountType = request.Debtor?.AccountType ?? string.Empty,
                            DebtorAgentBIC = request.Debtor?.AgentBIC ?? string.Empty,
                            DebtorIssuer = !string.IsNullOrWhiteSpace(request.Debtor?.Issuer) ? request.Debtor!.Issuer : "C",
                            CreditorName = request.Creditor?.Name ?? string.Empty,
                            CreditorAddress = request.Creditor?.Address ?? string.Empty,
                            CreditorAccount = request.Creditor?.Account ?? string.Empty,
                            CreditorAccountType = request.Creditor?.AccountType ?? string.Empty,
                            CreditorAgentBIC = request.Creditor?.AgentBIC ?? string.Empty,
                            CreditorIssuer = !string.IsNullOrWhiteSpace(request.Creditor?.Issuer) ? request.Creditor!.Issuer : "C",
                            RemittanceInformation = request.Ustrd ?? string.Empty,
                            Date = request.CreDt != default ? request.CreDt : DateTime.UtcNow,
                            ToBIC = request.To ?? string.Empty,
                            SettlementMethod = request.SettlementMethod.ToString(),
                            ChargeBearer = request.ChargeBearer.ToString(),
                            BizMsgIdr = request.BizMsgIdr ?? string.Empty,
                            MsgDefIdr = request.MsgDefIdr ?? string.Empty,
                            ClearingSystem = request.ClearingSystem ?? string.Empty,
                            MsgId = request.MsgId ?? string.Empty
                        };
                        BillReferenceMapper.Apply(dto);

                        // Create a bounded cancellation token for CoreBank callback
                        using var coreBankCts = CancellationTokenSource.CreateLinkedTokenSource(gct);
                        coreBankCts.CancelAfter(TimeSpan.FromSeconds(_core.CoreBankTimeoutSeconds > 0 ? _core.CoreBankTimeoutSeconds : 3));

                        SIPS.ISO20022.Models.DTOs.Response<System.Text.Json.Nodes.JsonObject?>? result = null;
                        using (SipsMetrics.TrackStep("Incoming", "Transaction", "CoreBankCall"))
                        {
                            result = await _callbacks.SendJsonAsync(
                                _callbackLinks.Transfer!,
                                headers,
                                dto,
                                CB_PaymentRequest,
                                _jsonAdapter,
                                _correlation,
                                _jsonSerializerOptions,
                                _callback,
                                coreBankCts.Token,
                                cid
                            );
                        }

                        if (result?.Data != null)
                        {
                            var cbResponse = ParseCallbackResult(result.Data);
                            if (IsCoreBankSuccess(cbResponse.Status))
                            {
                                _logger.LogInformation("[{CorrelationId}] CoreBank returned success status {Status} for transaction {TxId}. Proceeding with ACSC.", cid, cbResponse.Status, request.TxId);
                                response.AcceptanceDate = IsoResponseGuard.ValidAcceptanceDate(cbResponse.AcceptanceDate, request.CreDt);
                                if (cbResponse.AcceptanceDate != null && response.AcceptanceDate == null)
                                    _logger.LogWarning("[{CorrelationId}] Ignoring impossible CoreBank acceptance timestamp {AcceptanceDate} for TxId {TxId}.", cid, cbResponse.AcceptanceDate, request.TxId);
                            }
                            else if (string.Equals(cbResponse.Status?.Trim(), RJCT, StringComparison.OrdinalIgnoreCase))
                            {
                                _logger.LogInformation("[{CorrelationId}] CoreBank explicitly rejected transaction {TxId}. Reason: {Reason}", cid, request.TxId, cbResponse.Reason);
                                response.Status = RJCT;
                                response.Reason = "MS03";
                                response.AdditionalInfo = IsoText.StatusAdditionalInfo(
                                    cbResponse.AdditionalInfo,
                                    cbResponse.Reason);
                            }
                            else
                            {
                                var returnedStatus = string.IsNullOrWhiteSpace(cbResponse.Status) ? "<empty>" : cbResponse.Status;
                                _logger.LogWarning("[{CorrelationId}] CoreBank returned non-success status {Status} for transaction {TxId}. Rejecting for safety.", cid, returnedStatus, request.TxId);
                                response.Status = RJCT;
                                response.Reason = "MS03";
                                response.AdditionalInfo = IsoText.StatusAdditionalInfo(
                                    cbResponse.AdditionalInfo,
                                    cbResponse.Reason,
                                    $"CoreBank returned non-success status: {returnedStatus}.");
                            }
                        }
                        else
                        {
                            _logger.LogWarning("[{CorrelationId}] CoreBank callback returned null or empty data for TxId {TxId}. Fast-failing with RJCT (Safe mode).", cid, request.TxId);
                            response.Status = RJCT;
                            response.Reason = "MS03";
                            response.AdditionalInfo = "CoreBank returned empty response.";
                        }
                    }
                    catch (TaskCanceledException ex) when (!gct.IsCancellationRequested)
                    {
                        path = "CoreBankTimeout";
                        _logger.LogWarning(ex, "[{CorrelationId}] [MANUAL_RECONCILIATION_REQUIRED:POTENTIAL_PHANTOM_CREDIT] CoreBank callback timed out for TxId {TxId} (>{Timeout}s). Raising CheckStatus for audit trail.", cid, request.TxId, _core.CoreBankTimeoutSeconds);
                        
                        response.Status = RJCT;
                        response.Reason = "MS03";
                        response.AdditionalInfo = "CoreBank response exceeded internal SLA.";

                        // [AUDIT-GRADE INTEGRITY]: Record "in-doubt" state in immutable ledger
                        var ev = new
                        {
                            schemaVersion = 1,
                            eventId = Guid.NewGuid(),
                            actor = "System",
                            @event = "CheckStatusRaised",
                            reason = "CoreBankTimeout",
                            timestampUtc = DateTimeOffset.UtcNow,
                            slaContext = new { elapsedMs = sw.ElapsedMilliseconds, isoPath = path },
                            correlation = new { transactionId = request.TxId, msgId = request.MsgId, uetr = request.UETR, endToEndId = request.EndToEndId },
                            coreBank = new { idempotencyKey = request.TxId, timeoutSeconds = _core.CoreBankTimeoutSeconds },
                            reconciliationState = "Open"
                        };
                        
                        await _isoService.AppendAuditLedgerEventAsync(record.Id, ev, gct);
                    }
                    catch (Exception ex)
                    {
                        path = "CoreBankError";
                        _logger.LogWarning(ex, "[{CorrelationId}] Failed to call CoreBank for TxId {TxId} (Connectivity issue). Rejecting for safety.", cid, request.TxId);
                        response.Status = RJCT;
                        response.Reason = "MS03";
                        response.AdditionalInfo = "Failed to reach CoreBank for authorization.";
                    }
                }

                // [PERSIST-BEFORE-RETURN INVARIANT]: Build response XML and persist BEFORE returning
                if (!string.Equals(response.Status, RJCT, StringComparison.OrdinalIgnoreCase) && response.AcceptanceDate == null)
                {
                    response.AcceptanceDate = DateTime.UtcNow;
                }

                var rsp = PaymentRequestResponseBuilder.Build(response);
                var finalStatus = path == "CoreBankTimeout"
                    ? TransactionStatus.CheckStatus
                    : string.Equals(response.Status, RJCT, StringComparison.OrdinalIgnoreCase)
                        ? TransactionStatus.Failed
                        : TransactionStatus.Pending;
                
                // DB persistence should also respect the global deadline
                using var dbCts = CancellationTokenSource.CreateLinkedTokenSource(gct);
                dbCts.CancelAfter(TimeSpan.FromSeconds(_core.DbPersistTimeoutSeconds > 0 ? _core.DbPersistTimeoutSeconds : 10));
                
                await _isoService.PersistTransactionResponseAsync(record,
                    finalStatus,
                    !string.IsNullOrEmpty(response.Reason) ? response.Reason : (finalStatus == TransactionStatus.CheckStatus ? "CoreBank Timeout - Verification Required" : "Transaction Is Pending For Approval"),
                    response.AdditionalInfo,
                    rsp,
                    request.TxId ?? string.Empty,
                    request.EndToEndId ?? string.Empty,
                    dbCts.Token);

                _logger.LogInformation("[{CorrelationId}] pacs.008 initiation complete for TxId {TxId}. Status={Status}. Response persisted. Awaiting pacs.002 completion from IPS.", cid, request.TxId, response.Status);

                return FinalizeResponse(rsp, cid, sw, path);

            }
            catch (Exception ex)
            {
                path = path == "Normal" ? "DbFail" : path;
                _logger.LogError(ex, "[{CorrelationId}] Internal catch for TxId {TxId}. Path={Path}. Always returning signed ISO response for SLA compliance.", cid, request?.TxId, path);
                
                var rspFallback = BuildSafeRejectedPaymentResponse(
                    response,
                    request,
                    "Service failed to process callback within SLA.");
                var rspBody = PaymentRequestResponseBuilder.Build(rspFallback);
                
                // Final attempt to record the failure in DB (brief timeout)
                try {
                    using var dbCts2 = new CancellationTokenSource(TimeSpan.FromMilliseconds(500));
                    await _isoService.PersistTransactionResponseAsync(record,
                        TransactionStatus.Failed,
                        "Internal System Error during processing",
                        rspFallback.AdditionalInfo,
                        rspBody,
                        request?.TxId ?? string.Empty,
                        request?.EndToEndId ?? string.Empty,
                        dbCts2.Token);
                } catch { /* suppress DB logging errors in emergency fallback */ }
                
                return FinalizeResponse(rspBody, cid, sw, path);
            }
        }
        catch (Exception ex)
        {
            path = "EmergencyCatch";
            _logger.LogCritical(ex, "[{CorrelationId}] [METRIC:ISO_EMERGENCY_PATH] Catastrophic failure for TxId {TxId}. Path={Path}", cid, request?.TxId, path);
            // [PROTOCOL]: admi.002 for catastrophic technical failure (SmartVista spec)
            var err = SipsReject.Create(message, AdminRejectReasonCodes.TechnicalError, "Critical failure during processing.");
            return FinalizeResponse(err, cid, sw, path);
        }
    }

    private string FinalizeResponse(string isoBody, string cid, System.Diagnostics.Stopwatch sw, string path)
    {
        long elapsedMs = sw.ElapsedMilliseconds;
        long remainingSlaMs = (_core.CallbackSlaSeconds * 1000) - elapsedMs;

        _logger.LogInformation("[{CorrelationId}] [METRIC:ISO_PATH={Path}] Processing complete. Elapsed={ElapsedMs}ms, RemainingSLA={RemainingSlaMs}ms", cid, path, elapsedMs, remainingSlaMs);

        try
        {
            return _signer.SignEnvelope(isoBody);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[{CorrelationId}] [METRIC:ISO_SIGNING_FAILED] Failed to sign ISO response. The request will fail rather than return unauthenticated XML.", cid);
            throw;
        }
    }

    private static bool StoredResponseMatchesRequest(string responseXml, PaymentRequestBuilder.Request request)
    {
        try
        {
            var document = System.Xml.Linq.XDocument.Parse(responseXml);
            var related = document.Descendants().FirstOrDefault(e => e.Name.LocalName == "Rltd");
            if (related == null) return false;

            static string? Value(System.Xml.Linq.XElement parent, string name) =>
                parent.Descendants().FirstOrDefault(e => e.Name.LocalName == name)?.Value;
            static string? PartyValue(System.Xml.Linq.XElement parent, string partyName) =>
                parent.Elements().FirstOrDefault(e => e.Name.LocalName == partyName)?
                    .Descendants().FirstOrDefault(e => e.Name.LocalName == "Id")?.Value;
            static bool SameInstant(string? serialized, DateTime expected)
            {
                if (!DateTimeOffset.TryParse(serialized, out var actual)) return false;
                var expectedUtc = expected.Kind switch
                {
                    DateTimeKind.Utc => expected,
                    DateTimeKind.Local => expected.ToUniversalTime(),
                    _ => DateTime.SpecifyKind(expected, DateTimeKind.Utc)
                };
                return actual.UtcDateTime == expectedUtc;
            }

            var originalInfo = document.Descendants().FirstOrDefault(e => e.Name.LocalName == "OrgnlGrpInf");
            var appHeader = document.Descendants().FirstOrDefault(e => e.Name.LocalName == "AppHdr");
            return appHeader != null
                && string.Equals(appHeader.Elements().FirstOrDefault(e => e.Name.LocalName == "MsgDefIdr")?.Value, SupportedMessageTypes.CreditTransferResponse.Id, StringComparison.Ordinal)
                && string.Equals(PartyValue(related, "Fr"), request.From, StringComparison.Ordinal)
                && string.Equals(PartyValue(related, "To"), request.To, StringComparison.Ordinal)
                && string.Equals(Value(related, "BizMsgIdr"), request.BizMsgIdr, StringComparison.Ordinal)
                && string.Equals(Value(related, "MsgDefIdr"), request.MsgDefIdr, StringComparison.Ordinal)
                && SameInstant(Value(related, "CreDt"), request.CreDt)
                && originalInfo != null
                && string.Equals(Value(originalInfo, "OrgnlMsgId"), request.MsgId, StringComparison.Ordinal)
                && string.Equals(Value(originalInfo, "OrgnlMsgNmId"), request.MsgDefIdr, StringComparison.Ordinal)
                && SameInstant(Value(originalInfo, "OrgnlCreDtTm"), request.CreDt)
                && string.Equals(Value(document.Root!, "OrgnlTxId"), request.TxId, StringComparison.Ordinal);
        }
        catch
        {
            return false;
        }
    }

    private static PaymentRequestResponseBuilder.Response BuildSafeRejectedPaymentResponse(
        PaymentRequestResponseBuilder.Response current,
        PaymentRequestBuilder.Request? request,
        string fallbackDetail)
    {
        var original = request ?? current.Original ?? new PaymentRequestBuilder.Request();
        var previousReason = current.Reason;

        return new PaymentRequestResponseBuilder.Response
        {
            From = !string.IsNullOrWhiteSpace(current.From) ? current.From : original.To,
            To = !string.IsNullOrWhiteSpace(current.To) ? current.To : original.From,
            MsgDefIdr = !string.IsNullOrWhiteSpace(current.MsgDefIdr) ? current.MsgDefIdr : original.MsgDefIdr,
            BizMsgIdr = !string.IsNullOrWhiteSpace(current.BizMsgIdr) ? current.BizMsgIdr : original.BizMsgIdr,
            MsgId = !string.IsNullOrWhiteSpace(current.MsgId) ? current.MsgId : original.MsgId,
            CreDt = current.CreDt == default ? original.CreDt : current.CreDt,
            Original = original,
            Status = RJCT,
            Reason = "MS03",
            AdditionalInfo = IsoText.StatusAdditionalInfo(
                current.AdditionalInfo,
                IsoText.IsSafeMax35Text(previousReason) ? null : previousReason,
                fallbackDetail)
        };
    }

    private PaymentResponseDto ParseCallbackResult(JsonObject data)
    {
        var js = data;
        var md = _jsonAdapter.Transform(js!, "CB_PaymentResponse");
        var cb = _jsonAdapter.ToObject<SIPS.ISO20022.Models.DTOs.CB.CBPaymentStatusResponseDto>(md);
        if (cb == null)
            return new PaymentResponseDto { Status = string.Empty, TxId = string.Empty };

        return new PaymentResponseDto
        {
            Status = cb.Status ?? string.Empty,
            TxId = cb.TxId ?? string.Empty,
            AcceptanceDate = cb.AcceptanceDate,
            AdditionalInfo = cb.AdditionalInfo,
            Reason = cb.Reason,
            EndToEndId = cb.EndToEndId ?? string.Empty
        };
    }

    private static bool IsCoreBankSuccess(string? status)
    {
        var normalizedStatus = status?.Trim();
        return string.Equals(normalizedStatus, ACSC, StringComparison.OrdinalIgnoreCase)
            || string.Equals(normalizedStatus, "ACCP", StringComparison.OrdinalIgnoreCase)
            || string.Equals(normalizedStatus, "SUCC", StringComparison.OrdinalIgnoreCase);
    }
}
