using System.Text.Json;
using System.Text.Json.Serialization;
using SIPS.Adapter;
using SIPS.ISO20022.Helpers;
using SIPS.ISO20022.Interfaces;
using SIPS.ISO20022.Options;
using SIPS.PostgreSQL.Interfaces;
using SIPS.XMLDsig.Xades.Interfaces;
using SIPS.XMLDsig.Xades.Services;
using Microsoft.Extensions.Logging;
using SIPS.Core.Services.Verification;
using SIPS.Core.Services.ISOParsers;
using SIPS.Core.Services.Callback;
using SIPS.Core.Services.Responses;
using SIPS.Core.Services.Persistence;
using SIPS.Core.Services.Correlation;
using SIPS.Core.Services.Abstractions;
using SIPS.Core.Services.Implementations;
using SIPS.PostgreSQL.Enums;
using System.Text.Json.Nodes;
using SIPS.ISO20022.Models.DTOs;
using SIPS.ISO20022.Models.DTOs.CB;
using Microsoft.Extensions.Options;
using SIPS.Core.Options;
namespace SIPS.Core.Services;

/// <summary>
/// Handles incoming pacs.008 payment requests from SmartVista IPS.
/// 
/// IMPORTANT: SmartVista IPS Switch Behavior
/// ==========================================
/// When we receive a pacs.008, it has been REGENERATED by the SmartVista switch:
/// 
/// 1. Original Bank → Switch:
///    - Sending bank creates pacs.008 with their BizMsgIdr, CreDt, signature
///    
/// 2. Switch → Us (this handler):
///    - Switch REGENERATES AppHdr with NEW BizMsgIdr and CreDt
///    - Switch PRESERVES the original bank's signature (document:Sgntr)
///    - Switch PRESERVES the entire document payload (FIToFICstmrCdtTrf)
///    - The AppHdr.Fr will be the switch ID (e.g., "FP"), not the original bank
///    
/// 3. Our Response (pacs.002):
///    - We respond with pacs.002 immediately (ACSC status)
///    - Rltd block references the SWITCH-GENERATED message we received
///    - NOT the original bank's message (which we never saw)
///    - Transaction remains Pending until we receive completion notification
///    
/// 4. Completion Flow:
///    - Switch forwards our pacs.002 to the original bank
///    - Switch sends us a completion notification (pacs.002) after settlement
///    - We respond to the completion notification
///    - Only then do we call CoreBank to credit the account
///    
/// CORRELATION:
/// ===========
/// - We use TxId for correlation (constant throughout the flow)
/// - BizMsgIdr changes at every hop and cannot be used for correlation
/// - The signature verification proves the original bank's authenticity
/// </summary>
public sealed class IncomingTransactionHandler(
    ISO20022Options options,
    ILogger<IncomingTransactionHandler> logger,
    INativeSigner signer,
    IJsonAdapter jsonAdapter,
    IPaymentRequestParser parser,
    ICallbackClient callback,
    IResponseFactory responseFactory,
    ICorrelationService correlation,
    IInboundMessageService inbound,
    ICallbackOrchestrator callbacks,
    IISOMessageService isoService,
    IOptions<CoreOptions> coreOptions
    ) : IIncomingTransactionHandler
{
    private readonly ISO20022Options _callbackLinks = options;
    private readonly ILogger<IncomingTransactionHandler> _logger = logger;
    private readonly INativeSigner _signer = signer;
    private readonly IJsonAdapter _jsonAdapter = jsonAdapter;
    private readonly IPaymentRequestParser _parser = parser;
    private readonly ICallbackClient _callback = callback;
    private readonly IResponseFactory _responses = responseFactory;
    private readonly ICorrelationService _correlation = correlation;
    private readonly IInboundMessageService _inbound = inbound;
    private readonly ICallbackOrchestrator _callbacks = callbacks;
    private readonly IISOMessageService _isoService = isoService;
    private readonly CoreOptions _core = coreOptions.Value;
    private readonly JsonSerializerOptions _jsonSerializerOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) }
    };

    // Compatibility constructor for tests and existing code paths (14 args)
    public IncomingTransactionHandler(
        ISO20022Options options,
        ILogger<IncomingTransactionHandler> logger,
        IInterfaceHttpClient httpClient,
        INativeSigner signer,
        INativeVerifier verifier,
        IJsonAdapter jsonAdapter,
        IIncomingRecorder record,
        ISignatureService signature,
        IPaymentRequestParser parser,
        ICallbackClient callback,
        IResponseFactory responseFactory,
        IPersistenceGateway persistence,
        ICorrelationService correlation,
        IOptions<CoreOptions> coreOptions)
        : this(options, logger, signer, jsonAdapter, parser, callback, responseFactory, correlation,
              new InboundMessageService(signature),
              new CallbackOrchestrator(),
              new ISOMessageService(persistence),
              coreOptions)
    {
    }

    // Legacy Primary Constructor (17 args) - Restored for test compatibility
    public IncomingTransactionHandler(
        ISO20022Options options,
        ILogger<IncomingTransactionHandler> logger,
        IInterfaceHttpClient httpClient,
        INativeSigner signer,
        INativeVerifier verifier,
        IJsonAdapter jsonAdapter,
        IIncomingRecorder record,
        ISignatureService signature,
        IPaymentRequestParser parser,
        ICallbackClient callback,
        IResponseFactory responseFactory,
        IPersistenceGateway persistence,
        ICorrelationService correlation,
        IInboundMessageService inbound,
        ICallbackOrchestrator callbacks,
        IISOMessageService isoService,
        IOptions<CoreOptions> coreOptions)
        : this(options, logger, signer, jsonAdapter, parser, callback, responseFactory, correlation, inbound, callbacks, isoService, coreOptions)
    {
    }
    public async Task<string> HandleAsync(string message, CancellationToken ct)
    {
        // correlation id
        string cid = _correlation.Create();

        // Step 1: Verify signature and parse message via helper
        var (isValid, request) = await _inbound.VerifyAndParseAsync(
            message,
            (xml) =>
            {
                if (!_parser.TryParse(xml, out var req)) return (false, (PaymentRequestBuilder.Request?)null);
                return (true, req);
            },
            ct,
            cid);
        if (!isValid || request == null)
            return AdminMessage.Generate("Failed to verify the signature or parse the message.");
        // Step 2: Record the incoming ISO message via service
        var record = await _isoService.RecordIncomingTransactionAsync(request, message, ct);

        // Step 3: Prepare response object
        var response = _responses.BuildPaymentInitial(request);

        // CoreBank Integration (Optional)
        if (_core.IncludeCoreBankOnListing)
        {
            try
            {
                var headers = new Dictionary<string, string>() {
                        { API_Key, _callbackLinks.Key! },
                        { API_Secret, _callbackLinks.Secret! }
                    };
                // Idempotency key
                if (!string.IsNullOrWhiteSpace(request.TxId))
                    headers["X-Idempotency-Key"] = request.TxId;
                if (!string.IsNullOrWhiteSpace(request.TxId))
                    headers["X-Transaction-Id"] = request.TxId;

                var dto = new CBPaymentRequestDto
                {
                    FromBIC = request.From ?? string.Empty,
                    LocalInstrument = string.Empty, 
                    CategoryPurpose = string.Empty,
                    EndToEndId = request.EndToEndId ?? string.Empty,
                    TxId = request.TxId ?? string.Empty,
                    Amount = request.Amount,
                    Currency = request.Currency ?? string.Empty,
                    DebtorName = request.Debtor?.Name ?? string.Empty,
                    DebtorAccount = request.Debtor?.Account ?? string.Empty,
                    DebtorAccountType = request.Debtor?.AccountType ?? string.Empty,
                    DebtorAgentBIC = string.Empty,
                    DebtorIssuer = string.Empty,
                    CreditorName = request.Creditor?.Name ?? string.Empty,
                    CreditorAccount = request.Creditor?.Account ?? string.Empty,
                    CreditorAccountType = request.Creditor?.AccountType ?? string.Empty,
                    CreditorAgentBIC = string.Empty,
                    CreditorIssuer = string.Empty,
                    RemittanceInformation = string.Empty,
                    Date = DateTime.UtcNow,
                    ToBIC = request.To ?? string.Empty,
                    SettlementMethod = "CLRG",
                    ChargeBearer = "SLEV",
                    BizMsgIdr = request.BizMsgIdr ?? string.Empty,
                    MsgDefIdr = request.MsgDefIdr ?? string.Empty,
                    ClearingSystem = string.Empty,
                    MsgId = request.MsgId ?? string.Empty
                };

                var result = await _callbacks.SendJsonAsync(
                    _callbackLinks.Transfer!,
                    headers,
                    dto,
                    CB_PaymentRequest,
                    _jsonAdapter,
                    _correlation,
                    _jsonSerializerOptions,
                    _callback,
                    ct,
                    cid
                );

                if (result?.Data != null)
                {
                    var cbResponse = ParseCallbackResult(result.Data);
                    if (cbResponse.Status == RJCT)
                    {
                        _logger.LogWarning("[{CorrelationId}] CoreBank rejected transaction {TxId}. Returning RJCT.", cid, request.TxId);
                        response.Status = RJCT;
                        response.Reason = cbResponse.Reason;
                        response.AdditionalInfo = cbResponse.AdditionalInfo;
                    }
                    else
                    {
                        _logger.LogInformation("[{CorrelationId}] CoreBank returned status {Status} for transaction {TxId}. Proceeding with ACSC.", cid, cbResponse.Status, request.TxId);
                    }
                }
                else
                {
                    _logger.LogWarning("[{CorrelationId}] CoreBank callback returned null or empty data for TxId {TxId}. Proceeding with ACSC.", cid, request.TxId);
                }
            }
            catch (Exception ex)
            {
                 _logger.LogError(ex, "[{CorrelationId}] Failed to call CoreBank for TxId {TxId}. Proceeding with ACSC.", cid, request.TxId);
            }
        }

        try
        {
            using var dbCts = new System.Threading.CancellationTokenSource(System.TimeSpan.FromSeconds(_core.DbPersistTimeoutSeconds > 0 ? _core.DbPersistTimeoutSeconds : 10));
            var dbCt = dbCts.Token;
            
            // Step 4: Determine final status
            // If response.Status was set to RJCT by CoreBank logic, use it.
            // Otherwise default to ACSC (Pending).
            if (response.Status != RJCT)
            {
                response.Status = ACSC;
                response.Reason = string.Empty;
                response.AdditionalInfo = string.Empty;
            }

            // Step 5: Build and persist initial ACK response
            // Transaction remains in Pending state regardless of RJCT/ACSC return to switch, 
            // as downstream completion/reversal will finalize the state.
            var rsp = PaymentRequestResponseBuilder.Build(response);
            await _isoService.PersistTransactionResponseAsync(record,
                TransactionStatus.Pending,
                !string.IsNullOrEmpty(response.Reason) ? response.Reason : "Transaction Is Pending For Approval",
                response.AdditionalInfo,
                rsp,
                request.TxId ?? string.Empty,
                request.EndToEndId ?? string.Empty,
                dbCt);

            _logger.LogInformation("[{CorrelationId}] pacs.008 initiation complete for TxId {TxId}. Status={Status}. Awaiting pacs.002 completion from IPS.", cid, request.TxId, response.Status);

            return _signer.SignEnvelope(rsp);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[{CorrelationId}] INCOMING PS Handler Exception for TxId {TxId}", cid, request?.TxId);
            response.AdditionalInfo = "Failed to process Transaction";
            var rsp = PaymentRequestResponseBuilder.Build(response);
            using var dbCts2 = new System.Threading.CancellationTokenSource(System.TimeSpan.FromSeconds(_core.DbPersistTimeoutSeconds > 0 ? _core.DbPersistTimeoutSeconds : 10));
            await _isoService.PersistTransactionResponseAsync(record,
                TransactionStatus.Failed,
                "Failed to process Transaction",
                response.AdditionalInfo,
                rsp,
                request?.TxId ?? string.Empty,
                request?.EndToEndId ?? string.Empty,
                dbCts2.Token);
            return _signer.SignEnvelope(rsp);
        }
    }

    private PaymentResponseDto ParseCallbackResult(JsonObject data)
    {
        var js = data;
        var md = _jsonAdapter.Transform(js!, "CB_PaymentResponse");
        var cb = _jsonAdapter.ToObject<SIPS.ISO20022.Models.DTOs.CB.CBPaymentStatusResponseDto>(md);
        if (cb == null)
            return new PaymentResponseDto { Status = string.Empty, TxId = string.Empty };

        return new PaymentResponseDto
        {
            Status = cb.Status ?? string.Empty,
            TxId = cb.TxId ?? string.Empty,
            AcceptanceDate = cb.AcceptanceDate,
            AdditionalInfo = cb.AdditionalInfo,
            Reason = cb.Reason,
            EndToEndId = cb.EndToEndId ?? string.Empty
        };
    }
}