<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>SIPS.Core</PackageId>
    <Version>2.2.6</Version>
    <Authors>Abdulshakur Ahmed</Authors>
    <Product>SIPS Core</Product>
    <Description>SIPS CORE</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>LGPL-2.0-only</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" Version="0.9.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>true</Pack>
      <PackagePath>README.md</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SIPS.Adapter" Version="1.0.2" />
    <PackageReference Include="SIPS.PostgreSQL" Version="1.0.3" />
    <PackageReference Include="SIPS.Emv" Version="1.0.3" />
    <PackageReference Include="SIPS.ISO20022" Version="1.1.4" />
    <PackageReference Include="SIPS.XMLDsig.Xades" Version="1.0.9" />
  </ItemGroup>
</Project>