<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>SIPS.PostgreSQL</PackageId>
    <Version>1.0.4</Version>
    <Authors>Abdulshakur Ahmed</Authors>
    <Product>SIPS PostgreSQL</Product>
    <Description>SIPS PostgreSQL</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>LGPL-2.0-only</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>true</Pack>
      <PackagePath>README.md</PackagePath>
    </None>
  </ItemGroup>

</Project>